version: 2


builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
    binary: derper
    dir: $GOPATH/bin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: "Tailscale <info@tailscale.com>"
    homepage: "https://github.com/tailscale/derper"
    license: "MIT"
    description: "DERP (Designated Encrypted Relay for Packets) server"
    vendor: "Tailscale"
    formats:
      - deb
      - rpm
    dependencies:
      - ca-certificates
    scripts:
      postinstall: |
        #!/bin/sh
        systemctl daemon-reload
        systemctl enable derper
        systemctl start derper

release:
  name_template: "{{ .ProjectName }} {{ .Version }}"
  extra_files:
    - glob: packaging/derper.service

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch 